### ISSUE TITLE
SEO matters

### ISSUE THREAD

**Issue by pmelchor** [citation-style-language/citation-style-language.github.io#2]
- Compare old vs new: URLs, titles, descriptions
- Prepare 301 redirects for any non-matching URLs

**Comment by rmzelle** [comment]
(if you're also going to do the blog post URLs, it looks like http://citationstyles.org/2016/10/06/by-htm/ was changed as well during the hacks)

**Comment by rmzelle** [comment]
(it used to be http://web.archive.org/web/20161022122121/http://citationstyles.org/2016/10/06/mendeley-and-elsevier-donation-for-2016/ [minus the web-archive bit of course])

**Comment by rmzelle** [comment]
And there are some old redirects set up in WordPress too. I'm not sure if it's still worth it to migrate those over, but we should at least review them.

**Comment by pmelchor** [comment]
Blog post URLs: I had that covered, thanks (see https://citation-style-language.github.io/2016/10/06/mendeley-and-elsevier-donation-for-2016/).

I will check the Wordpress redirects.

**Comment by rmzelle** [comment]
@pmelchor, all the content should be moved over from the WordPress site (with some minor editing), so this is probably the main thing to wrap up before we throw the switch and go live.

> Compare old vs new: URLs, titles, descriptions

What do you mean with "titles" and "descriptions"? Was there anything other than the main pages and blog post URLs that you wanted to check?

https://citation-style-language.github.io/authors/ vs. http://citationstyles.org/styles/
https://citation-style-language.github.io/2016/10/06/mendeley-and-elsevier-donation-for-2016/ vs http://citationstyles.org/2016/10/06/mendeley-and-elsevier-donation-for-2016/
etc.

Looks like setting up redirects is easy with https://help.github.com/articles/redirects-on-github-pages/, by the way.

**Comment by pmelchor** [comment]
Looking at the source HTML for https://citation-style-language.github.io/authors/ it looks like our `<title>` tags are fine...
`<title>Authors - Citation Style Language</title>`

... but that we are using the same meta description on all the pages:
`<meta name="description" content="CitationStyles.org is the home of the Citation Style Language (CSL), a popular open XML-based language to describe the formatting of citations and bibliographies.">`

We should have that particular description on the homepage only and have unique descriptions for each of the other pages. For Authors it could be something along the lines of:
`<meta name="description" content="Are you an author or academic using CSL-based software? Learn how to find, install and use CSL citation styles.">`

Description tags are important for SEO and they are displayed in search results on Google, so we want them to be short but "keyword-rich" —as in the above example—.

In terms of URLs we should be fine since I managed to 'fake' the Wordpress permalink structure on Jekyll. There will be few redirections and we just have to make sure the response code is 301 (permanent redirect).

**Comment by rmzelle** [comment]
Hand-checked the URLs:

http://citationstyles.org/
https://citation-style-language.github.io

http://citationstyles.org/styles/
https://citation-style-language.github.io/authors/
(!; redirect from /styles/ to /authors/)

http://citationstyles.org/blog/
https://citation-style-language.github.io/blog/

http://citationstyles.org/developers/
https://citation-style-language.github.io/developers/

http://citationstyles.org/publishers/
https://citation-style-language.github.io/publishers/

http://citationstyles.org/about/
https://citation-style-language.github.io/about/

http://citationstyles.org/contact/
https://citation-style-language.github.io/contact/

http://citationstyles.org/2010/03/22/citation-style-language-1-0/
https://citation-style-language.github.io/2010/03/22/citation-style-language-1-0/

http://citationstyles.org/2010/05/30/csl-1-0-specification-update-2010-05-30/
https://citation-style-language.github.io/2010/05/30/csl-1-0-specification-update-2010-05-30/

http://citationstyles.org/2011/03/18/csl-1-0-first-anniversary/
https://citation-style-language.github.io/2011/03/18/csl-1-0-first-anniversary/

http://citationstyles.org/2012/09/03/citation-style-language-1-0-1-update/
https://citation-style-language.github.io/2012/09/03/citation-style-language-1-0-1-update/

http://citationstyles.org/2014/01/29/mendeley-donates-to-the-csl-project/
https://citation-style-language.github.io/2014/01/29/mendeley-donates-to-the-csl-project/

http://citationstyles.org/2015/05/20/papers-and-springer-donation/
https://citation-style-language.github.io/2015/05/20/papers-and-springer-donation/

http://citationstyles.org/2015/07/21/mendeley-and-elsevier-donation-for-2015/
https://citation-style-language.github.io/2015/07/21/mendeley-and-elsevier-donation-for-2015/

http://citationstyles.org/2016/10/06/mendeley-and-elsevier-donation-for-2016/
https://citation-style-language.github.io/2016/10/06/mendeley-and-elsevier-donation-for-2016/

Looks like we only need 1 redirect for the current site. Haven't checked the old redirects in WordPress yet.

**Comment by rmzelle** [comment]
> it looks like http://citationstyles.org/2016/10/06/by-htm/ was changed as well during the hacks

I just restored this to http://citationstyles.org/2016/10/06/mendeley-and-elsevier-donation-for-2016/ for the old site.

**Comment by rmzelle** [comment]
WordPress redirects:

`/citation-style-language/documentation/` to `/styles/` (should become `/authors/`)
`/citation-style-language/schema/` to `/developers/`
`/styles/style-repository/` to `/styles/` (should become `/authors/`)
`/citation-style-language/editing-styles/` to `/styles/` (should become `/authors/`)
`/),/` to `/` (pretty sure we can drop this)

(all of these are pretty old, so I'm not sure they're still necessary)

**Comment by rmzelle** [comment]
I'll close this since we took care of the page descriptions. I created a new issue for page redirects at #26.
