### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/citation-style-language.github.io#25]
@dstillman (rightly) suggested the font size is a little out of whack, which seems like a relatively common complaint with our minimal-mistakes theme. The theme author explains below how to globally adjust the font size:

https://github.com/mmistakes/minimal-mistakes/issues/1219
https://github.com/mmistakes/minimal-mistakes/issues/1043

**Comment by rmzelle** [comment]
@pmelchor, can I leave this for you for when you have some time in December? The effect PR #28 isn't great, and I get the sense you're a little bit more comfortable with CSS. You'll probably want to wait until after you update the theme with upstream changes.

The site looks fine on my iPhone SE, but the margins and font sizes seem a bit too big for smaller laptop screens such as 1280x800.

**Comment by pmelchor** [comment]
Sure, I will take care of this :-)

**Comment by pmelchor** [comment]
PR https://github.com/citation-style-language/citation-style-language.github.io/pull/33 improves some of this.

I will do some more work on margins and proportions.

**Comment by pmelchor** [comment]
I would close this issue once we merge PR https://github.com/citation-style-language/citation-style-language.github.io/pull/35

@rmzelle feel free to open additional issues if there are any other tweaks you would like to see done.
