### ISSUE TITLE
Make http://docs.citationstyles.org/ HTTPS

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/citation-style-language.github.io#39]
Requires upstream support at Read the Docs. See https://github.com/rtfd/readthedocs.org/issues/2652.

Last remaining piece of the CSL website that isn't HTTPS yet. (see also https://github.com/citation-style-language/citation-style-language.github.io/issues/37)

**Comment by rmzelle** [comment]
This was fixed in August 2018: https://github.com/rtfd/readthedocs.org/issues/2652#issuecomment-410385213

Still waiting for Read the Docs to support automatic HTTPS redirects: https://github.com/rtfd/readthedocs.org/issues/4641

**Comment by adam3smith** [comment]
I think we can close this -- https is enabled, even if redirect isn't automated.

**Comment by rmzelle** [comment]
Sure. Not sure if we'll have to do anything once automatic redirects are offered, although we do already have "Always use HTTPS for this domain" checked for Read the Docs.
