### ISSUE TITLE
Move table of contents to the left sidebar

### ISSUE THREAD

**Issue by pmelchor** [citation-style-language/citation-style-language.github.io#4]

**Comment by rmzelle** [comment]
Make it floating too, perhaps? (assuming it fits on one page)

**Comment by pmelchor** [comment]
Yes, that is exactly what I am up to.

The theme is ready for that when working with "collections" (subsections of the website made up of multiple pages). You can see a dummy example of that type of floating sidebar menu [here](https://citation-style-language.github.io/developers/)—). However, that type of navigation is not available for linking to headings in the same page, as is the case in [Authors](https://citation-style-language.github.io/authors/).

I am halfway through with the coding that will cover that second scenario.

**Comment by rmzelle** [comment]
See https://github.com/mmistakes/minimal-mistakes/issues/1298 for some related discussion.

Unless this is easy to get working, it might be easier to first complete a production-ready version of the site (hopefully in the next week or two), and revert your preliminary work on a floating TOC for now. We can then later re-add it via a pull request. Looks like most of the work on this was done in https://github.com/citation-style-language/citation-style-language.github.io/commit/f414d0e0cb6d18abc19af0a77fe4e480b75cb29e ?

**Comment by rmzelle** [comment]
I would also be fine with the standard TOCs, at least initially. My main issue with those is that you if you navigate to a section (e.g. https://citation-style-language.github.io/authors/#requesting-new-styles), the URL doesn't change to include the page anchor of the selected section (the browser just stays on https://citation-style-language.github.io/authors/), so you can't use the browser's back-button to go back to the top of the page.

**Comment by rmzelle** [comment]
> My main issue with those is that you if you navigate to a section (e.g. https://citation-style-language.github.io/authors/#requesting-new-styles), the URL doesn't change to include the page anchor of the selected section

This issue is discussed at https://github.com/mmistakes/minimal-mistakes/issues/1302.

**Comment by pmelchor** [comment]
> Unless this is easy to get working, it might be easier to first complete a production-ready version of the site (hopefully in the next week or two), and revert your preliminary work on a floating TOC for now. We can then later re-add it via a pull request

I would definitely go for that. In Christmas I can look into recovering the previous commit and/or even code something specific to get all we want (left side, floating, anchor in URLs).

**Comment by rmzelle** [comment]
I didn't revert https://github.com/citation-style-language/citation-style-language.github.io/commit/f414d0e0cb6d18abc19af0a77fe4e480b75cb29e yet, just used the standard "single" page layout for the developers page to (temporary) hide your work-in-progress.

**Comment by pmelchor** [comment]
> I would also be fine with the standard TOCs, at least initially. My main issue with those is that you if you navigate to a section (e.g. https://citation-style-language.github.io/authors/#requesting-new-styles), the URL doesn't change to include the page anchor of the selected section (the browser just stays on https://citation-style-language.github.io/authors/), so you can't use the browser's back-button to go back to the top of the page.

@rmzelle, I have addressed this issue in PR https://github.com/citation-style-language/citation-style-language.github.io/pull/36

I would leave the sidebar as is for now and consider the left-side, floating version when we are ready to use it (e.g. maybe if we move forward with consolidating the documentation under citationstyles.org).
