### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by pmelchor** [citation-style-language/citation-style-language.github.io#6]
GitHub Pages does not support contact forms "per se". However there are [several solutions](https://www.quora.com/How-do-I-add-a-working-contact-form-on-a-Github-pages-website).

For now I have implemented [Simple Form](https://getsimpleform.com/) because I like their using a token instead of an email address that is visible in the source code.

@rmzelle I will configure Simple Form with the same email address now used in http://citationstyles.org/contact/ so that you can test it. I will let you know once it is done.

**Comment by rmzelle** [comment]
Works for me! I replaced the API token with one that sends emails to me in https://github.com/citation-style-language/citation-style-language.github.io/pull/15.
