### ISSUE TITLE
Developers page

### ISSUE THREAD

**Issue by pmelchor** [citation-style-language/citation-style-language.github.io#7]
Move content over from Wordpress and merge with content from the "Styles" page that did not fit in "Authors".

**Comment by rmzelle** [comment]
@pmelchor, I fully agree that an "Authors" section is much clearer than the "Styles" section on the old site, but I disagree with the [content](https://github.com/citation-style-language/citation-style-language.github.io/blob/fb23126bbfedb1c433bb56b0d80e415faab01862/_pages/developers.md) you're moving over to the "Developers" page. How styles localize, what the limitations of CSL are, and how styles can be edited, are all topics of interest to authors, so I think I'll just put it back in the Authors section.

Sorry! :)

**Comment by bdarcus** [comment]
Probably a misunderstanding of what we mean by "developers" there, which is
people interested in coding or using code to process or work with styles,
but NOT the process of developing styles.

**Comment by pmelchor** [comment]
@rmzelle Sure, it's 100% your call :-)

Just to clarify, when I first proposed creating creating an "Authors" page [here](https://github.com/citation-style-language/styles/issues/2314#issuecomment-273854490) I was thinking of academics who:

- just want to find and use the right CSL style with Zotero (or similar tools)
- often have very basic IT skills
- and approach CSL from a user perspective (they want the functionality but don't care about how it works behind the scenes).

My idea was to move all the technical stuff to "Developers" and limit the info in "Authors" to how to find styles, how to request new styles, etc.

I think that what is important is that we aim for the structure that will make more sense to non-CSL-insiders visiting the website.

As to what that structure is... I trust your understanding of the project much more than mine :-)

**Comment by rmzelle** [comment]
Yes, I think we should be following the split suggested by @bdarcus. The developers section should be primarily aimed at integrators, i.e. programmers that want to add CSL support to their own software. The authors section would be for users of tools built on top of CSL. We shouldn't hide things like how to edit or localize styles from the latter group, even if it gets a bit more complicated. (we should just aim to make those things that are complicated for regular users simpler)
